# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 04:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardinfo', '0002_fileuploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=127, null=True, verbose_name='File Name')),
                ('csv_file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='File')),
            ],
        ),
        migrations.RemoveField(
            model_name='fileuploads',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='FileUploads',
        ),
    ]
