# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardinfo', '0003_auto_20171022_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
