# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 07:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardinfo', '0004_fileupload_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='bank_cif',
            field=models.CharField(max_length=127, verbose_name='Bank CIF '),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_cif',
            field=models.CharField(max_length=127, verbose_name='Card CIF '),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_cvv',
            field=models.CharField(max_length=127, verbose_name='CVV '),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(max_length=127, verbose_name='Card Number '),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='name_on_card',
            field=models.CharField(max_length=127, verbose_name='Name On card '),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='national_id',
            field=models.CharField(max_length=13, verbose_name='National ID '),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='csv_file',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv'])], verbose_name='File '),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file_name',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='File Name '),
        ),
    ]
