# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 04:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Name ')),
                ('circuit_id', models.IntegerField(verbose_name='Circuit ID ')),
                ('brief_description', models.TextField(verbose_name='Brief Description ')),
                ('operating_time', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Operating Time ')),
                ('head_office_address', models.TextField(verbose_name='Head Office Address ')),
                ('camels', models.CharField(max_length=50, verbose_name='CAMELS ')),
                ('earnings_per_share', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Earnings Per Share ')),
            ],
        ),
    ]
