# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankinfo', '0003_auto_20171129_0710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branche',
            new_name='Branch',
        ),
    ]
