# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankinfo', '0004_auto_20171129_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='ATM Name ')),
                ('address', models.TextField(verbose_name='ATM Address')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankinfo.Bank', verbose_name='Bank ')),
            ],
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='branch_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='branch_name',
            new_name='name',
        ),
    ]
