# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankinfo', '0006_auto_20171129_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='earnings_per_share',
            new_name='earning_per_share',
        ),
    ]
