# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 09:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankinfo', '0007_auto_20171129_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtmBooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='ATM Name ')),
                ('status', models.BooleanField(default=True, verbose_name='Status ')),
                ('location', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Location ')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankinfo.Bank', verbose_name='Bank ')),
            ],
        ),
        migrations.RemoveField(
            model_name='atm',
            name='bank',
        ),
        migrations.DeleteModel(
            name='ATM',
        ),
    ]
