# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankinfo', '0008_auto_20171129_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, verbose_name='About ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email ')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone Number ')),
                ('camels', models.CharField(max_length=50, verbose_name='CAMELS ')),
                ('address', models.TextField(blank=True, verbose_name='Address ')),
                ('registered', models.CharField(blank=True, max_length=50, verbose_name='Registered ')),
            ],
        ),
        migrations.RemoveField(
            model_name='bank',
            name='about',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='camels',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='email',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='operating_hours',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='registered',
        ),
        migrations.AlterField(
            model_name='atmbooth',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='bankinfo.Bank', verbose_name='Bank '),
        ),
        migrations.AddField(
            model_name='bank',
            name='details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bankinfo.BankDetails', verbose_name='Details'),
        ),
    ]
