# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankinfo', '0010_auto_20171129_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('suday', 'sunday'), ('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday')], max_length=30, verbose_name='Day ')),
                ('start', models.TimeField(verbose_name='Start ')),
                ('end', models.TimeField(verbose_name='End ')),
            ],
        ),
        migrations.AlterField(
            model_name='atmbooth',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atm_booths', to='bankinfo.Bank', verbose_name='Bank '),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='bankinfo.Bank', verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='operatinghour',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='bankinfo.BankDetails', verbose_name='Operating Hours '),
        ),
    ]
