# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankinfo', '0013_auto_20171203_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='earning_per_share',
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='earning_per_share',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Earnings Per Share '),
            preserve_default=False,
        ),
    ]
